runtime: go
api_version: go1
application: rtek-cloud
version: 1

skip_files: |
    ^(.*/)?(
    (app\.yaml)|
    )$

handlers:

- url: /css
  static_dir: css
  expiration: "1m"
  mime_type: text/css
  secure: always
  
- url: /js
  static_dir: js
  expiration: "1m"
  mime_type: text/javascript
  secure: always
  
- url: /font
  static_dir: font
  expiration: "1m"
  secure: always
  
- url: /lib
  static_dir: lib
  expiration: "1m"
  mime_type: text/css
  secure: always
  
- url: /img
  static_dir: img
  expiration: "1m"
  secure: always

- url: /.*
  script: _go_app
